# Generated by Django 5.0.14 on 2025-06-07 06:48

import django.db.models.deletion
import django.utils.timezone
import filemanager.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.TextField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("directory", "Directory"),
                            ("symlink", "Symlink"),
                        ],
                        default="file",
                        max_length=20,
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("encoding", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=filemanager.models.upload_to_user_directory,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="filemanager.fileitem",
                    ),
                ),
            ],
            options={
                "ordering": ["file_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FileActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Uploaded"),
                            ("downloaded", "Downloaded"),
                            ("viewed", "Viewed"),
                            ("modified", "Modified"),
                            ("deleted", "Deleted"),
                            ("shared", "Shared"),
                            ("renamed", "Renamed"),
                            ("moved", "Moved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="filemanager.fileitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FilePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_public", models.BooleanField(default=False)),
                ("allow_download", models.BooleanField(default=True)),
                ("allow_upload", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("max_downloads", models.IntegerField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "file_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=filemanager.models.upload_to_user_directory
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="filemanager.fileitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["owner", "is_deleted"], name="filemanager_owner_i_8b843a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["parent", "file_type"], name="filemanager_parent__0858ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(fields=["path"], name="filemanager_path_affa93_idx"),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["mime_type"], name="filemanager_mime_ty_17af98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["created_at"], name="filemanager_created_a933a7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fileitem",
            constraint=models.UniqueConstraint(
                fields=("path", "owner"), name="unique_path_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="fileactivity",
            index=models.Index(
                fields=["file_item", "activity_type"],
                name="filemanager_file_it_b5425c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileactivity",
            index=models.Index(
                fields=["user", "created_at"], name="filemanager_user_id_498b72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileactivity",
            index=models.Index(
                fields=["created_at"], name="filemanager_created_ab993b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filepermission",
            index=models.Index(
                fields=["file_item", "user"], name="filemanager_file_it_353b74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filepermission",
            index=models.Index(
                fields=["user", "permission_type"],
                name="filemanager_user_id_ab32dc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filepermission",
            unique_together={("file_item", "user", "permission_type")},
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["share_token"], name="filemanager_share_t_342bda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["shared_by", "is_active"], name="filemanager_shared__d1f974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["file_item", "version_number"],
                name="filemanager_file_it_d9d51f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["created_at"], name="filemanager_created_c317ad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_item", "version_number")},
        ),
    ]
