# Generated by Django 5.0.14 on 2025-06-07 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filemanager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("text_analysis", "Text Analysis"),
                            ("image_analysis", "Image Analysis"),
                            ("document_analysis", "Document Analysis"),
                            ("code_analysis", "Code Analysis"),
                            ("translation", "Translation"),
                            ("summarization", "Summarization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("endpoint_url", models.URLField(blank=True, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_type", "is_active"],
                        name="ai_integrat_model_t_d9bff4_idx",
                    ),
                    models.Index(fields=["name"], name="ai_integrat_name_14ab48_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Analysis"),
                            ("file_analysis", "File Analysis"),
                            ("image_analysis", "Image Analysis"),
                            ("batch_analysis", "Batch Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_data", models.TextField()),
                ("output_data", models.TextField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="ai_integration.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="ai_integrat_user_id_3f1751_idx"
                    ),
                    models.Index(
                        fields=["analysis_type", "status"],
                        name="ai_integrat_analysi_ecb045_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_integrat_created_8e911e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("avg_response_time", models.DurationField(blank=True, null=True)),
                ("avg_tokens_per_request", models.FloatField(default=0.0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("user_satisfaction", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="ai_integration.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("ai_model", "date")},
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("template", models.TextField()),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("text_analysis", "Text Analysis"),
                            ("image_analysis", "Image Analysis"),
                            ("document_analysis", "Document Analysis"),
                            ("code_analysis", "Code Analysis"),
                            ("translation", "Translation"),
                            ("summarization", "Summarization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variable names used in template",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "created_by")},
            },
        ),
        migrations.CreateModel(
            name="AIUsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_processing_time",
                    models.DurationField(default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
